<a href="https://colab.research.google.com/github/AnkitaAnalytics/Python-for-Data-Science/blob/main/Buffet_Details.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [6]:
buffet_data = [['A1', 'Shilpa',18,'Indian',24.65],
               ['A2','Jaspreet',32,'American',18.54],
               ['A3','Dominic',19,'Indian',	27.66],
               ['A4','Ahmad',22,'American',19.54],
               ['A5','Joseph',28,'Indian',17.32],]
buffet_cols=['Room',	'Name',	'Age',	'Cuisine',	'Expenditure']
df_buffet = pd.DataFrame(data=buffet_data,columns=buffet_cols)

In [7]:
df_buffet.head()

  Room      Name  Age   Cuisine  Expenditure
0   A1    Shilpa   18    Indian        24.65
1   A2  Jaspreet   32  American        18.54
2   A3   Dominic   19    Indian        27.66
3   A4     Ahmad   22  American        19.54
4   A5    Joseph   28    Indian        17.32

### Access the 'Cuisine' column in the dataframe

In [10]:
#method 1 - square bracket notation is used to access a specific column in Pandas
df_buffet['Cuisine']

0      Indian
1    American
2      Indian
3    American
4      Indian
Name: Cuisine, dtype: object

In [14]:
# method 2- get() method is used to access a single column in Pandas
df_buffet.get('Cuisine')

0      Indian
1    American
2      Indian
3    American
4      Indian
Name: Cuisine, dtype: object

### Find the average age of customers

In [15]:
df_buffet['Age'].mean()

23.8

### filter the dataframe to include only rows where the 'Expenditure' is less than 20

In [16]:

df_buffet[df_buffet['Expenditure'] < 20]

  Room      Name  Age   Cuisine  Expenditure
1   A2  Jaspreet   32  American        18.54
3   A4     Ahmad   22  American        19.54
4   A5    Joseph   28    Indian        17.32